# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-05-25 21:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portsite', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.PositiveIntegerField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='project',
            name='project_date',
            field=models.DateField(),
        ),
        migrations.AddField(
            model_name='project',
            name='details',
            field=models.ManyToManyField(blank=True, to='portsite.Details'),
        ),
    ]
