# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-05-25 21:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portsite', '0002_auto_20200525_2125'),
    ]

    operations = [
        migrations.AddField(
            model_name='details',
            name='detail_id',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='details',
            name='order_number',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
