# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-05-25 21:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portsite', '0003_auto_20200525_2132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
