# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-06-10 19:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portsite', '0004_auto_20200525_2159'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='url_link',
            field=models.URLField(blank=True),
        ),
    ]
