# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-06-29 19:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portsite', '0005_project_url_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('quote', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='project',
            name='url_link',
        ),
        migrations.AddField(
            model_name='project',
            name='URL_link',
            field=models.TextField(blank=True),
        ),
    ]
