# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-08-10 21:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portsite', '0006_auto_20200629_1946'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='YT_Link',
            field=models.TextField(blank=True),
        ),
    ]
