# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-08-10 21:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portsite', '0007_project_yt_link'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='YT_Link',
            new_name='YT_link',
        ),
    ]
